name: Realtime Node

on:
  push:
    branches:
      - main

jobs:
  node-realtime:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Set environment
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env

      - name: Start server with PM2
        run: |
          npx pm2 start index.js --name realtime --no-daemon
